source "$HOME/.config/bash/shell.sh"
source "$HOME/.config/bash/aliases.sh"
source "$HOME/.config/bash/functions.sh"
source "$HOME/.config/bash/init.sh"
source "$HOME/.config/bash/env.sh"
[[ $- == *i* ]] && bind -f "$HOME/.config/bash/inputrc.sh"
